### ISSUE TITLE
List of problematic endpont for ols4

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [TIBHannover/ols4#71]
**Describe the bug**
Here is a list of all endpoints that cause issues or raise an exception

- [x] #77
- [x] #83
- [x] 3- **Search**:  field "expanded" is missing from the search reult for ols4 v1. Look at: https://github.com/EBISPOT/ols4/issues/763
- [x] 4- **js tree** for root terms: [/api/ontologies/vibso/terms/](url)http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000001/jstree/children/0  --> resolved, look at: https://github.com/EBISPOT/ols4/issues/645
- [x] 5- **Search** returns 500 from start=40:  [/api/search?q=data&start=40&groupField=iri&rows=20](url)  --> it seems to happen on the query "data". Maybe related to 1 ?
- [x] 6- **Search** filter based on a collection returns nothing. https://github.com/TIBHannover/ols4/issues/72
- [x] 7- **Select**: ontology_prefix is sometimes missing from the select result. https://github.com/TIBHannover/ols4/issues/73
- [x] 8- **Graph** endpont returns 500: [/api/ontologies/vibso/terms http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000070/graph](url)
- [x] 9- **js tree**:  viewMode=all does not work in ols4 v1. https://github.com/TIBHannover/ols4/issues/74

### Update 14.11.2024

- [x] list of collections returns 500: [api/ontologies/getstatisticsbyschema?schema=collection](url)
- [x] relatedform returns nothing: [api/ontologies/vibso/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000070/relatedfroms](url)
- [x] equivalent class description returns nothing: [ api/ontologies/vibso/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000070/equivalentclassdescription](url)
- [x] super class description returns nothing: [api/ontologies/vibso/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000070/superclassdescription](url)
- [x] term instances returns 404:  [api/ontologies/vibso/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000070/terminstances](url)
- [x] #99
- [x] **annotations** field is null for ontologies.[ api/ontologies/vibso](url) --> current version: https://service.tib.eu/ts4tib/api/ontologies/vibso
